package morse.android.theme

import androidx.compose.ui.graphics.Color

val LightSurface = Color(0xFFFFFFFF)
val LightSurfaceVariant = Color(0xFFF5F7FA)
val LightSurfaceContainer = Color(0xFFEEF2F6)
val LightOnSurface = Color(0xFF1C1C1E)
val LightOnSurfaceVariant = Color(0xFF6E6E73)
val LightOutline = Color(0xFFC7CDD6)
val LightOutlineVariant = Color(0xFFE4E8EE)
val LightPrimary = Color(0xFF1A73E8)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFDCEBFF)
val LightOnPrimaryContainer = Color(0xFF0D47A1)
val LightSecondary = Color(0xFF0D47A1)
val LightSecondaryContainer = Color(0xFFDDE7F7)
val LightTertiary = Color(0xFF5B6F91)
val LightTertiaryContainer = Color(0xFFE6ECF5)
val LightSuccess = Color(0xFF34A853)
val LightSuccessContainer = Color(0xFFD9F2E0)
val LightError = Color(0xFFEA4335)
val LightErrorContainer = Color(0xFFFDE2DF)
val LightSignalActive = Color(0xFF1A73E8)
val LightSignalGlow = Color(0xFFA9D1FF)
val LightRewardAmber = Color(0xFFFBBC04)

val DarkSurface = Color(0xFF0E0E10)
val DarkSurfaceVariant = Color(0xFF1C1C1E)
val DarkSurfaceContainer = Color(0xFF232327)
val DarkOnSurface = Color(0xFFF2F2F7)
val DarkOnSurfaceVariant = Color(0xFF8E8E93)
val DarkOutline = Color(0xFF575A61)
val DarkOutlineVariant = Color(0xFF33363B)
val DarkPrimary = Color(0xFF4DA3FF)
val DarkOnPrimary = Color(0xFF062041)
val DarkPrimaryContainer = Color(0xFF0D47A1)
val DarkOnPrimaryContainer = Color(0xFFD6EAFF)
val DarkSecondary = Color(0xFF82C4FF)
val DarkSecondaryContainer = Color(0xFF163B63)
val DarkTertiary = Color(0xFFA8BAD6)
val DarkTertiaryContainer = Color(0xFF24364D)
val DarkSuccess = Color(0xFF30D158)
val DarkSuccessContainer = Color(0xFF13371C)
val DarkError = Color(0xFFFF453A)
val DarkErrorContainer = Color(0xFF601611)
val DarkSignalActive = Color(0xFF82C4FF)
val DarkSignalGlow = Color(0x664DA3FF)
val DarkRewardAmber = Color(0xFFFFD60A)

// Exercise mode accents
val ListenPurple = Color(0xFF8B5CF6)
val ListenPurpleDark = Color(0xFFA78BFA)
val DecodeTeal = Color(0xFF14B8A6)
val DecodeTealDark = Color(0xFF2DD4BF)
val EncodeOrange = Color(0xFFF97316)
val EncodeOrangeDark = Color(0xFFFB923C)
